wandb_version: 1

epochs:
  desc: null
  value: 20
classes:
  desc: null
  value: 10
kernels:
  desc: null
  value:
  - 16
  - 32
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.003
dataset:
  desc: null
  value: MNIST-digit
architecture:
  desc: null
  value: CNN
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697018391.079412
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 3
      - 16
      - 23
      4: 3.9.17
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
